name: CI Training Model

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn mlflow

      - name: Run training
        run: |
          cd MLProject
          python modelling.py

      - name: Commit artifacts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .
          git commit -m "Save artifacts" || echo "No changes"
          git push
