name: CI Training Model

on:
  push:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn mlflow dagshub matplotlib seaborn joblib

      - name: Show MLproject
        run: |
          cat MLProject/MLproject

      - name: Run MLflow Project
        run: |
          mlflow run MLProject
